### Introduction to positional embedding (without being trained on any parameters)
1. Collect the data and do data sampling using dataloaders and datasets.
2. Convert text into token and token id's using BPE algorithm.
3. Represent token id's into vector representation using vector embeddings (feature dimensions, vocab_size)
4. Now, represent this token embeddings to do positional embedding (absolute or relative) to make each token in position to each other.

In [4]:
#Importing raw dataset from text file
with open("../datasets/verdict.txt", "r", encoding="utf-8") as f:
    raw_data = f.read()

In [9]:
# Dataset class to have data in batches input-target pair
import torch
import torch.nn as nn
import tiktoken
from torch.utils.data import Dataset, DataLoader

class GPTDatasetsV1(Dataset):

    def __init__(self, text, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        #Encoding the text with help of tokenizer
        tokens =  tokenizer.encode(text, allowed_special= {"<|endoftext|>"})

        #Determining max_length, stride of each batch_size of text
        for i in range(0, len(tokens) - max_length, stride):
            input_chunks = tokens[i: i + max_length]
            target_chunks = tokens[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunks))
            self.target_ids.append(torch.tensor(target_chunks))

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

    def __len__(self):
        return len(self.input_ids)


# Dataloader function to load the datasets in batches of size and do parallel processing in batches for multiple GPU architectures

def data_loader_V1(text, batch_size= 8, max_length= 4, stride= 4, num_workers= 0, shuffle= False, drop_last= False):
    # Defining tokeizer to run the encode for text
    tokenizer = tiktoken.get_encoding("gpt2")

    # Preparing datasets to be loaded in batches
    load_dataset = GPTDatasetsV1(text, tokenizer, max_length, stride)

    # Running dataloder call with dataset values
    dataloader = DataLoader(
        load_dataset,
        batch_size= batch_size,
        shuffle= shuffle,
        num_workers= num_workers,
        drop_last= drop_last,
    )

    return dataloader

In [6]:
# Get the input-target pair of input_ids and target_ids in batches

data_loader = data_loader_V1(raw_data)
data_iter = iter(data_loader)
input, target = next(data_iter)

print(f'Input Token batch Matrix: \n {input}')
print(f'Target Token batch Matrix: \n {target}')

Input Token batch Matrix: 
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Target Token batch Matrix: 
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [7]:
# Step 3:- Converting these input tokens id matrix into vector embeddings
# Our input batch matrix has shape, 8 * 4 (batch_size * context_length)
# The vector embedding matrix for this batch will be 8 * 4 * 256 (batch_size, context length, number of feature per token id's)
vocab_size = 50257
feature_dims = 256

# Initializing Embedding matrix with random values
vector_embeddings_layer = torch.nn.Embedding(vocab_size, feature_dims)

# Converting input-target matrix into token embeddings (8, 4, 256)
token_embeddings = vector_embeddings_layer(input)

print(f'Token Embedding layer shape: {token_embeddings.shape}')

Token Embedding layer shape: torch.Size([8, 4, 256])


In [8]:
# Step 4:- Converting Token Embedding layer + adding positional embedding layer to get input embeddings to feed to transformer layer
context_window = max_length = 4

positional_embedding_layer = torch.nn.Embedding(context_window, feature_dims)

# Making positional embedding matrix with dim (4 * 256)
positional_embedding = positional_embedding_layer(torch.arange(context_window))
print(f'Positional Embedding Shape: {positional_embedding.shape}')


# Adding Token/Vector embeddings + Positional embeddings = input embeddings
input_embeddings = token_embeddings + positional_embedding

print(f'Without Optimized Input Embedding Matrix: \n {input_embeddings}')
print(f'Without Optimized Input Embedding Matrix Shape: \n {input_embeddings.shape}')

Positional Embedding Shape: torch.Size([4, 256])
Without Optimized Input Embedding Matrix: 
 tensor([[[-0.1822,  1.0748, -0.0403,  ..., -1.1262,  1.0615, -1.4988],
         [ 1.6480,  0.2555,  1.8971,  ..., -1.4520,  0.3637, -0.2610],
         [-0.2764, -0.3915,  0.2036,  ..., -2.5164,  1.4577, -2.2204],
         [ 1.2974,  0.4039,  1.8761,  ..., -2.2367,  0.5236,  2.1490]],

        [[ 1.2643,  2.5677, -0.2311,  ..., -3.2626, -0.8563, -2.6426],
         [ 2.2768, -0.1038, -0.0840,  ..., -1.2208,  1.7059,  0.1506],
         [-0.5692, -1.3402,  0.3044,  ..., -0.9372,  0.5526, -1.4349],
         [-0.0091, -2.6047,  0.3662,  ..., -1.4092, -0.0220,  0.9755]],

        [[ 0.9148,  1.8831,  2.0442,  ..., -0.4406, -2.0216, -2.9986],
         [ 1.8841, -0.3680,  0.3258,  ..., -1.2185,  0.1714,  1.0684],
         [-0.3311, -2.2549, -0.0330,  ..., -1.1625,  3.2520, -2.4444],
         [ 0.9597,  0.7112,  1.8132,  ...,  1.0526,  2.2907,  1.5454]],

        ...,

        [[-0.1544,  1.7097, -0.0674

### Understanding Positional Encoding (Relative)
- The below formulas are used to calculate the Positions of tokens in arbitary space 
- Calculation of Even Place in the token: - 
$$
PE_{(pos, 2i)} = \sin\left(\frac{pos}{10000^{\frac{2i}{d_{model}}}}\right)
$$
- Calculation of odd place in the token: - 
$$
PE_{(pos, 2i+1)} = \cos\left(\frac{pos}{10000^{\frac{2i}{d_{model}}}}\right)
$$

In [39]:
# Coding the Positional Encoding layer (Relative)
class PositionalEmbedding(nn.Module):
    def __init__(self, context_length: int, feature_dims: int):
        super().__init__()
        self.context_length = context_length
        self.feature_dims = feature_dims
        # Positional matrix of size (context_legth, feature_dims)
        pe = torch.zeros(context_length, feature_dims)
        position = torch.arange(0, context_length).unsqueeze(1) # matrix to keep track of token's position in each row
        # Calculation: - 2 * i / d_model (d_model = feature_dims)
        freq_scale = 2 * torch.arange(0, context_length) / feature_dims 
        # Calculation:- 10000^(2i/d_model)
        div_term = torch.pow(10000, freq_scale)

        # For even position, we are using sine distribution 
        pe[:, 0::2] = torch.sin(position * div_term)
        # For odd position, we are using cosine distribution
        pe[:, 1::2] = torch.cos(position * div_term) 
        
        # Adding batch_size to the positional encoding matrix 
        pe = pe.unsqueeze(0) # (batch_size, context_length, feature_dims)
        # Register this encoder as a buffer layer 
        self.register_buffer("positional_encoding", pe)
    
    def forward(self, x):
        return x + self.positional_encoding


In [40]:
# Example value 
input_embedding = torch.tensor([
    [0.02, 0.03, 0.04, 0.05, 0.06, 0.07], 
    [0.01, 0.21, 0.22, 0.12, 0.13, 0.14], 
    [0.14, 0.15, 0.26, 0.37, 0.17, 0.22], 
], dtype= torch.long) # dtype=long to make compatible with embedding layer

context_length = input_embedding.shape[0]
feature_dims = input_embedding.shape[1]

pe = PositionalEmbedding(context_length, feature_dims)
print(f"PositonalEmbedding.value: \n{pe(input_embedding)}")

PositonalEmbedding.value: 
tensor([[[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
         [ 0.8415,  0.5403,  0.4321, -0.9018, -0.7151,  0.6990],
         [ 0.9093, -0.4161, -0.7793,  0.6266, -0.9997, -0.0227]]])


In [43]:
ex = torch.arange(0, 6)
print(ex)

tensor([0, 1, 2, 3, 4, 5])
